config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles

  root to: 'articles#index'
  resources :comments
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    alias_action :update, :destroy, :to => :modify

    user ||= User.new

    if user.role? :admin
        can :manage, :all
    elsif user.role? :author
        # can :read, [Article, Comment]
        can :read, [Article, Comment]
        can :create, [Article, Comment]
        can :modify, Article do |article|
            article.user == user 
        end
    else
        can :read, [Article, Comment]
        can :create, Comment
        can :modify, Comment
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "Sorry, you can't access this page"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  # before_action :authenticate_user!, except: [:index]
  before_action :load_article, except:[:index, :new, :create]
  load_and_authorize_resource

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    current_user.article.create(article_params)
    redirect_to articles_path
  end

  def show
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to(articles_path)
  end

  def destroy
    @article.destroy
    redirect_to(articles_path)
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end

  def load_article
    @article = Article.find(params[:id]) 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  # before_action :authenticate_user!, except: [:index]
  # before_action :load_comment, except:[:new, :create]
  load_and_authorize_resource

  def index
  end

  def new
    @comment = Comment.new
  end

  def create
    current_user.comments.create(comment_params)
    redirect_to comments_path
  end

  def show
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to(comments_path)
  end

  def destroy
    @comment.destroy
    redirect_to(comments_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

  def load_comment
    @comment = Comment.find(params[:id]) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<%= link_to 'Add Comment', new_comment_path %>

<% @article.comments.each do |comment| %>
<p><%= comment.comment %>
<%= comment.user.name %></p>
<%= link_to 'Edit Comment', edit_comment_path %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit <%= @article.title %></h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% if can? :create, Article %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

<% @articles.each do |article| %>
  <p><%= article.title %>
  | <%= article.user.name %>
  | <%= link_to('Show', article_path(article)) %>
  <% if can? :modify, article %>
  | <%= link_to('Edit', edit_article_path(article)) %>
  | <%= link_to('Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}) %>
  <% end %>
  </p>
<% end %>

app/views/articles/new.html.erb
<h2>Create New Article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<h5> Written by: <%= @article.user.name %></h5>
<p><%= @article.content %></p>
<% if can? :modify, @article %>
<%= link_to('Edit', edit_article_path(@article)) %>
| <%= link_to('Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}) %>
<br>
<br>
<h3>Comments</h3>
<%= render 'comments' %>
<% end %>

app/views/comments/index.html.erb
<h1>This is Comment#index</h1>

<% @comment.each do |comment| %>
  <p><%= comment.comment %>
  | <%= comment.user.name %>
  | <%= link_to('Show', comment_path(article)) %>

  <% if can? :modify, comment %>
  | <%= link_to('Edit', edit_comment_path(article)) %>
  | <%= link_to('Delete', comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'}) %>
  <% end %>

  </p>
<% end %>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>This is Comment#show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiApp</title>
  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:700italic,500italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="mystyle.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class='login'>
  <% if current_user %>
    <%= current_user.email %>
    <%= link_to "log out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Register", new_user_registration_path %>
  <% end %>
</div>

<nav>
  <ul>
    <li><%= link_to 'Home', articles_path %></li>
  </ul>
</nav>

<%= yield %>

</body>
</html>